Cleanup ci workflows

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -4,16 +4,6 @@ name: "CD: Deploy site"
 on:
   release:
     types: [released]
-  # push:
-  #   branches:
-  #     - master
-  #   paths:
-  #     - "posts/**"
-  #     - "resources/**"
-  #     - "src/**"
-  #     - "templates/**"
-  #     - ".github/workflows/ci-cd.yml"
-  #     - "stack.yaml"
 
 concurrency: production
 
@@ -34,6 +24,7 @@ jobs:
         run: |
           gh release download --pattern "_site" --dir ./_site
           ls _site
+          [ -d "_site" ] || echo "Failed downloading the _site directory." && exit 1
 
       - name: Upload site to S3
         run: |
@@ -43,12 +34,12 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
-      # - name: Purge CloudFront cache
-      #   run: |
-      #     curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache" \
-      #       -H "Authorization: Bearer ${CLOUDFLARE_TOKEN}" \
-      #       -H "Content-Type: application/json" \
-      #       --data '{"purge_everything":true}'
-      #   env:
-      #     CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
-      #     CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
+      - name: Purge CloudFront cache
+        run: |
+          curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache" \
+            -H "Authorization: Bearer ${CLOUDFLARE_TOKEN}" \
+            -H "Content-Type: application/json" \
+            --data '{"purge_everything":true}'
+        env:
+          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
+          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
